In [3]:
import pandas as pd
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

In [4]:
housing = fetch_california_housing(as_frame=True).frame

In [5]:
housing.head()

   MedInc  HouseAge  AveRooms  ...  Latitude  Longitude  MedHouseVal
0  8.3252      41.0  6.984127  ...     37.88    -122.23        4.526
1  8.3014      21.0  6.238137  ...     37.86    -122.22        3.585
2  7.2574      52.0  8.288136  ...     37.85    -122.24        3.521
3  5.6431      52.0  5.817352  ...     37.85    -122.25        3.413
4  3.8462      52.0  6.281853  ...     37.85    -122.25        3.422

[5 rows x 9 columns]

In [6]:
# x = housing[["AveRooms"]]

x = housing[["MedInc"]]
y = housing["MedHouseVal"]

In [7]:
x_train,x_test,y_train,y_test= train_test_split(x,y,test_size=0.2,random_state=42)

In [8]:
model_linear=LinearRegression()
model_linear.fit(x_train,y_train)
y_pred_linear = model_linear.predict(x_test)

In [9]:
r2_score_linear = r2_score(y_test,y_pred_linear)
r2_score_linear

0.45885918903846656

In [10]:
x=housing.drop("MedHouseVal",axis=1)
y = housing["MedHouseVal"]

In [11]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)
model_linear.fit(x_train,y_train)
y_pred_linear2=model_linear.predict(x_test)
r2_score_linear2= r2_score(y_test,y_pred_linear2)
r2_score_linear2
# در مقایسه با تمرین اول میبینیم هرچه اطلاعات بیشتر باشه نتیجه هم بهتر است

0.575787706032451

In [12]:
from sklearn.preprocessing import PolynomialFeatures

In [13]:
x=housing.drop("MedHouseVal",axis=1)
y = housing["MedHouseVal"]


x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [14]:
poly = PolynomialFeatures(degree=2)
x_train_poly= poly.fit_transform(x_train)
x_test_poly=poly.transform(x_test)

In [15]:
model_linear.fit(x_train_poly,y_train)
y_pred_linear3=model_linear.predict(x_test_poly)
r2_score_linear3= r2_score(y_test,y_pred_linear3)
r2_score_linear3

0.5386643967063635

In [16]:
poly2 = PolynomialFeatures(degree=5)
x_train_poly2= poly2.fit_transform(x_train)
x_test_poly2=poly2.transform(x_test)

In [17]:
model_linear.fit(x_train_poly2,y_train)
y_pred_linear4 = model_linear.predict(x_test_poly2)
r2_score_linear4 = r2_score(y_test,y_pred_linear4)  
r2_score_linear4

0.00112857651778131

In [18]:
from sklearn.linear_model import Ridge,Lasso

In [19]:

x=housing.drop("MedHouseVal",axis=1)
y = housing["MedHouseVal"]

In [20]:
x_train,x_test,y_train,y_test=train_test_split(x,y, test_size=0.2, random_state=42)
ridge_model = Ridge(alpha=100)
ridge_model.fit(x_train,y_train)
y_pred_ridge = ridge_model.predict(x_test)
r2_score_ridge=r2_score(y_test,y_pred_ridge)
r2_score_ridge

0.5805278207071451

In [21]:
r2_score_linear

0.45885918903846656

In [22]:
lasso_model=Lasso(alpha=1)
lasso_model.fit(x_train,y_train)
y_pred_lasso = lasso_model.predict(x_test)
r2_score_lasso = r2_score(y_test,y_pred_lasso)
r2_score_lasso

0.2841671821008396

In [23]:
print(lasso_model.coef_)
#وقتی الفا 0.01 بود هیچ ضریبی صفر نشد ولی هرچه ضریب بالا رفت ضریب بیشتری صفر شدند

[ 1.48196324e-01  5.72821070e-03  0.00000000e+00  0.00000000e+00
 -8.16437293e-06 -0.00000000e+00 -0.00000000e+00 -0.00000000e+00]

In [24]:
from sklearn.model_selection import cross_val_score

In [25]:

x=housing.drop("MedHouseVal",axis=1)
y = housing["MedHouseVal"]

In [26]:
lasso_model=Lasso(alpha=1)
scores= cross_val_score(lasso_model,x,y,cv=5,scoring="neg_root_mean_squared_error")
scores

array([-0.97032398, -0.92211241, -1.07507034, -0.98048203, -1.04996119])

In [27]:
-scores.mean()

np.float64(0.9995899873740027)

In [28]:
lasso_model=Lasso(alpha=0.01)
scores2= cross_val_score(lasso_model,x,y,cv=5,scoring="neg_root_mean_squared_error")
scores2

array([-0.68343001, -0.80009433, -0.80648584, -0.75548715, -0.70121989])

In [29]:
-scores2.mean()

np.float64(0.7493434452234827)

In [60]:
from sklearn.datasets import load_diabetes
import numpy as np
import pandas as pd
from sklearn.metrics import mean_absolute_error,mean_squared_error

In [61]:
diabetes= load_diabetes()

In [62]:
diabetes.data
diabetes.target

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 288.,  88., 292.,  71.,
       197., 186.,  25.,  84.,  96., 195.,  53., 217., 172., 131., 214.,
        59.,  70., 220., 268., 152.,  47.,  74., 295., 101., 151., 127.,
       237., 225.,  81., 151., 107.,  64., 138., 185., 265., 101., 137.,
       143., 141.,  79., 292., 178.,  91., 116.,  86., 122.,  72., 129.,
       142.,  90., 158.,  39., 196., 222., 277.,  99., 196., 202., 155.,
        77., 191.,  70.,  73.,  49.,  65., 263., 248., 296., 214., 185.,
        78.,  93., 252., 150.,  77., 208.,  77., 108., 160.,  53., 220.,
       154., 259.,  90., 246., 124.,  67.,  72., 257., 262., 275., 177.,
        71.,  47., 187., 125.,  78.,  51., 258., 215., 303., 243.,  91.,
       150., 310., 153., 346.,  63.,  89.,  50.,  39., 103., 308., 116.,
       145.,  74.,  45., 115., 264.,  87., 202., 127., 182., 241.,  66.,
        94., 283.,  64., 102., 200., 265.,  94., 230., 181., 156., 233.,
        60., 219.,  80.,  68., 332., 248.,  84., 200.,  55.,  85.,  89.,
        31., 129.,  83., 275.,  65., 198., 236., 253., 124.,  44., 172.,
       114., 142., 109., 180., 144., 163., 147.,  97., 220., 190., 109.,
       191., 122., 230., 242., 248., 249., 192., 131., 237.,  78., 135.,
       244., 199., 270., 164.,  72.,  96., 306.,  91., 214.,  95., 216.,
       263., 178., 113., 200., 139., 139.,  88., 148.,  88., 243.,  71.,
        77., 109., 272.,  60.,  54., 221.,  90., 311., 281., 182., 321.,
        58., 262., 206., 233., 242., 123., 167.,  63., 197.,  71., 168.,
       140., 217., 121., 235., 245.,  40.,  52., 104., 132.,  88.,  69.,
       219.,  72., 201., 110.,  51., 277.,  63., 118.,  69., 273., 258.,
        43., 198., 242., 232., 175.,  93., 168., 275., 293., 281.,  72.,
       140., 189., 181., 209., 136., 261., 113., 131., 174., 257.,  55.,
        84.,  42., 146., 212., 233.,  91., 111., 152., 120.,  67., 310.,
        94., 183.,  66., 173.,  72.,  49.,  64.,  48., 178., 104., 132.,
       220.,  57.])

In [63]:
diabetes.data.shape

(442, 10)

In [64]:
df = pd.DataFrame(diabetes.data,columns=diabetes.feature_names)
df

          age       sex       bmi  ...        s4        s5        s6
0    0.038076  0.050680  0.061696  ... -0.002592  0.019907 -0.017646
1   -0.001882 -0.044642 -0.051474  ... -0.039493 -0.068332 -0.092204
2    0.085299  0.050680  0.044451  ... -0.002592  0.002861 -0.025930
3   -0.089063 -0.044642 -0.011595  ...  0.034309  0.022688 -0.009362
4    0.005383 -0.044642 -0.036385  ... -0.002592 -0.031988 -0.046641
..        ...       ...       ...  ...       ...       ...       ...
437  0.041708  0.050680  0.019662  ... -0.002592  0.031193  0.007207
438 -0.005515  0.050680 -0.015906  ...  0.034309 -0.018114  0.044485
439  0.041708  0.050680 -0.015906  ... -0.011080 -0.046883  0.015491
440 -0.045472 -0.044642  0.039062  ...  0.026560  0.044529 -0.025930
441 -0.045472 -0.044642 -0.073030  ... -0.039493 -0.004222  0.003064

[442 rows x 10 columns]

In [65]:
df["target"]=diabetes.target

In [66]:
df.head()

        age       sex       bmi        bp  ...        s4        s5        s6  target
0  0.038076  0.050680  0.061696  0.021872  ... -0.002592  0.019907 -0.017646   151.0
1 -0.001882 -0.044642 -0.051474 -0.026328  ... -0.039493 -0.068332 -0.092204    75.0
2  0.085299  0.050680  0.044451 -0.005670  ... -0.002592  0.002861 -0.025930   141.0
3 -0.089063 -0.044642 -0.011595 -0.036656  ...  0.034309  0.022688 -0.009362   206.0
4  0.005383 -0.044642 -0.036385  0.021872  ... -0.002592 -0.031988 -0.046641   135.0

[5 rows x 11 columns]

In [67]:
x=df.drop("target",axis=1)
y=df["target"]

In [68]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
Linear=LinearRegression()
Linear.fit(x_train,y_train)
y_pred_linear_df=Linear.predict(x_test)

In [69]:
mae=mean_absolute_error(y_test,y_pred_linear_df)
mae

42.79409467959994

In [70]:
rmse=np.sqrt(mean_squared_error(y_test,y_pred_linear_df))
rmse

np.float64(53.85344583676592)

In [58]:
r2_df=r2_score(y_test,y_pred_linear_df)
r2_df

0.4526027629719196